apiVersion: apps/v1
kind: Deployment
metadata:
  name: courseapp-deployment
spec:
  replicas: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: courseapp
  template:
    metadata:
      labels:
        app: courseapp
    spec:
      containers:
        - name: courseapp
          image: ashomni/course-app:v1.1
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: courseapp-config

          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
            
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3