apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-service

spec:
  type: {{ .Values.service.type }}

  selector:
    app: courseapp

  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000